server:
  port: 8006

# datasource
spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://ec2-3-144-213-215.us-east-2.compute.amazonaws.com:3306/userDB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update