server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rank
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: prod

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/blood_rank
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  profiles:
#    active: prod

#spring:
#  datasource:
#      platform: oracle
#      driver-class-name: oracle.jdbc.driver.OracleDriver
#      url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
#      username: local
#      password: local

  jpa:
    hibernate:
      ddl-auto: create #나중에 none으로 바꿔
    properties:
      hibernate:
        #         show_sql: true
        # show_sql : 옵션은 System.out 에 하이버네이트 실행 SQL을 남긴다.
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  #  org.hibernate.SQL : 옵션은 logger를 통해 하이버네이트 실행 SQL을 남긴다