server:
  port: 8080

# datasource
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/mainDB
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.h2.Driver

  # jpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug