server:
  port: 8004

spring:
  datasource:
    url: jdbc:mysql://ec2-3-144-213-215.us-east-2.compute.amazonaws.com:3306/mypageDB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: create #나중에 none으로 바꿔 update
    properties:
      hibernate:
        #         show_sql: true
        # show_sql : 옵션은 System.out 에 하이버네이트 실행 SQL을 남긴다.
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  #  org.hibernate.SQL : 옵션은 logger를 통해 하이버네이트 실행 SQL을 남긴다


