server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      force: true
  # 젠킨스테스트

# datasource
spring:
  datasource:
    # url: jdbc:h2:tcp://localhost/~/test
    # username: sa
    # password:
    # driver-class-name: org.h2.Driver
#    url: jdbc:mysql://${DATABASE_HOST}:3306/mainDB
    url: jdbc:mysql://localhost:3306/mainDB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
