spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/blood_rank
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: create #나중에 none으로 바꿔
    properties:
      hibernate:
        #         show_sql: true
        # show_sql : 옵션은 System.out 에 하이버네이트 실행 SQL을 남긴다.
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  #  org.hibernate.SQL : 옵션은 logger를 통해 하이버네이트 실행 SQL을 남긴다

server:
  port: 8000